config/routes.rb
DemoApp::Application.routes.draw do

  resources :projects do
    resources :todo_lists do
      resources :todo_items
    end
  end

end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  attr_accessible :desc, :status, :title

  belongs_to :todo_list
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  # GET /todo_items
  # GET /todo_items.json
  def index
    @todo_items = TodoItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @todo_items }
    end
  end

  # GET /todo_items/1
  # GET /todo_items/1.json
  def show
    @todo_item = TodoItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @todo_item }
    end
  end

  # GET /todo_items/new
  # GET /todo_items/new.json
  def new
    @todo_item = TodoItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @todo_item }
    end
  end

  # GET /todo_items/1/edit
  def edit
    @todo_item = TodoItem.find(params[:id])
  end

  # POST /todo_items
  # POST /todo_items.json
  def create
    @todo_list = TodoList.find(params[:todo_list_id])
    @todo_item = @todo_list.todo_items.build(params[:todo_item])

    respond_to do |format|
      if @todo_item.save
        format.js
        format.html { redirect_to @todo_item, notice: 'Todo item was successfully created.' }
        format.json { render json: @todo_item, status: :created, location: @todo_item }
      else                                            format.js

        format.html { render action: "new" }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /todo_items/1
  # PUT /todo_items/1.json
  def update
    @todo_item = TodoItem.find(params[:id])

    respond_to do |format|
      if @todo_item.update_attributes(params[:todo_item])
        format.js
        format.html { redirect_to @todo_item.todo_list.project, notice: 'Todo item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_items/1
  # DELETE /todo_items/1.json
  def destroy
    @todo_item = TodoItem.find(params[:id])
    @todo_item.destroy

    respond_to do |format|
      format.js
      format.html { redirect_to todo_items_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/views/todo_items/_form.html.erb
<%= form_for(@todo_item) do |f| %>
  <% if @todo_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_item.errors.count, "error") %> prohibited this todo_item from being saved:</h2>

      <ul>
      <% @todo_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_field :desc %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.number_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_items/_todo_item.erb
<li id="<%=dom_id(todo_item)%>">
    <%= best_in_place todo_item, :title, :path => project_todo_list_todo_item_path(todo_item.todo_list.project,todo_item.todo_list,todo_item) %>
    <%= link_to 'x', project_todo_list_todo_item_path(todo_item.todo_list.project,todo_item.todo_list,todo_item), method: :delete, :remote => true, data: { confirm: 'Are you sure?' } %>
</li>

app/views/todo_items/create.js.erb
var x = 1;
var new_item = "<%= escape_javascript(render(@todo_item)) %>";
var list_id = "<%=dom_id(@todo_item.todo_list)%>"

$("#"+list_id + " > div.todo_items > ul").append(new_item);
$("#"+list_id + " > div.todo_items > ul > li:last").effect('highlight')

app/views/todo_items/destroy.js.erb
$("#<%=dom_id(@todo_item)%>").fadeOut('slow');

app/views/todo_items/edit.html.erb
<h1>Editing todo_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo_item %> |
<%= link_to 'Back', todo_items_path %>

app/views/todo_items/index.html.erb
<h1>Listing todo_items</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Desc</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @todo_items.each do |todo_item| %>
  <tr>
    <td><%= todo_item.title %></td>
    <td><%= todo_item.desc %></td>
    <td><%= todo_item.status %></td>
    <td><%= link_to 'Show', [todo_item.todo_list, todo_item] %></td>
    <td><%= link_to 'Edit', edit_todo_item_path(todo_item) %></td>
    <td><%= link_to 'Destroy', todo_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Todo item', new_todo_item_path %>

app/views/todo_items/new.html.erb
<h1>New todo_item</h1>

<%= render 'form' %>

<%= link_to 'Back', todo_items_path %>

app/views/todo_items/show.html.erb
<div style="width:300px; float:left">

  <p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @todo_item.title %>
</p>

<p>
  <b>Desc:</b>
  <%= @todo_item.desc %>
</p>

<p>
  <b>Status:</b>
  <%= @todo_item.status %>
</p>


<%= link_to 'Edit', edit_todo_item_path(@todo_item) %> |
<%= link_to 'Back', todo_items_path %>
</div>
<div style="width:300px; float:left">

  <p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @todo_item.title %>
</p>

<p>
  <b>Desc:</b>
  <%= @todo_item.desc %>
</p>

<p>
  <b>Status:</b>
  <%= @todo_item.status %>
</p>


<%= link_to 'Edit', edit_todo_item_path(@todo_item) %> |
<%= link_to 'Back', todo_items_path %>
</div>