config/routes.rb
DemoApp::Application.routes.draw do

  resources :projects do
    resources :todo_lists do
      resources :todo_items
    end
  end

end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
  attr_accessible :title

  has_many :todo_items
  belongs_to :project
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @todo_lists }
    end
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
    @todo_list = TodoList.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @todo_list }
    end
  end

  # GET /todo_lists/new
  # GET /todo_lists/new.json
  def new
    @todo_list = TodoList.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @todo_list }
    end
  end

  # GET /todo_lists/1/edit
  def edit
    @todo_list = TodoList.find(params[:id])
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @project = Project.find(params[:project_id])
    @todo_list = @project.todo_lists.build(params[:todo_list])
    @new_item = TodoItem.new
    respond_to do |format|
      if @todo_list.save
        @todo_lists = @project.todo_lists
        format.js
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render json: @todo_list, status: :created, location: @todo_list }
      else
        format.html { render action: "new" }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /todo_lists/1
  # PUT /todo_lists/1.json
  def update

    @todo_list = TodoList.find(params[:id])

    respond_to do |format|
      if @todo_list.update_attributes(params[:todo_list])
        format.js
        format.html { redirect_to @todo_list.project, notice: 'Todo list was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @project = Project.find(params[:project_id])
    @todo_list = TodoList.find(params[:id])
    @todo_list.destroy
    @todo_lists = @project.todo_lists
    respond_to do |format|
      format.js
      format.html { redirect_to project_todo_lists_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/todo_lists/_form.html.erb
<%= form_for(@todo_list.project, @todo_list) do |f| %>
  <% if @todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
      <% @todo_list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_lists/_todo_list.html.erb
<div style="border: 1px dotted #2aa7ff" id="<%=dom_id(todo_list)%>">
  <div>
    <%= best_in_place todo_list, :title, :path => project_todo_list_path(todo_list.project, todo_list) %>
    <%= link_to 'x', project_todo_list_path(todo_list.project, todo_list), method: :delete, :remote => true, data: { confirm: 'Are you sure?' } %>
  </div>
  <a href="#" class="show_todo_items" style="margin-left:160px">Show/Hide Todo Items</a>
  <div style="border: 1px solid deeppink; margin: 10px;display: none" class="todo_items">
    <a href="#" class="open_new_todo_item_form">New Todo Item</a>
    <div style="display: none" class="new_todo_item_form">
      <%= form_for [@project, todo_list, @new_item], :remote => true do |f| %>
          <div class="field">
            <%= f.label :title %><br />
            <%= f.text_field :title %>
          </div>
          <%= f.submit %>

      <% end %>
    </div>
    <ul>
        <%= render(todo_list.todo_items) %>
    </ul>
  </div>
</div>

app/views/todo_lists/create.js.erb
var new_list = "<%= escape_javascript(render(@todo_list)) %>";
$(new_list).hide();

$("#todo_lists").append(new_list).show('slow');
$("#todo_lists > div:last").effect('highlight')

app/views/todo_lists/destroy.js.erb
$("#<%=dom_id(@todo_list)%>").fadeOut('slow');

app/views/todo_lists/edit.html.erb
<h1>Editing todo_list</h1>

<%= render 'form' %>

<%= link_to 'Show', [@todo_list.project, @todo_list] %> |
<%= link_to 'Back', project_todo_lists_path %>

app/views/todo_lists/index.html.erb
<h1>Listing todo_lists</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @todo_lists.each do |todo_list| %>
  <tr>
    <td><%= todo_list.title %></td>
    <td><%= link_to 'Show', [todo_list.project, todo_list] %></td>
    <td><%= link_to 'Edit', edit_project_todo_list_path(todo_list.project, todo_list) %></td>
    <td><%= link_to 'Destroy', [todo_list.project, todo_list], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Todo list', new_project_todo_list_path(params[:project_id]) %>

app/views/todo_lists/new.html.erb
<h1>New todo_list</h1>

<%= render 'form' %>

<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @todo_list.title %>
</p>

<%= link_to 'Edit', edit_project_todo_list_path(@todo_list.project, @todo_list) %> |
<%= link_to 'Back', project_todo_lists_path %>